version: "3"

tasks:
  default:
    - task: help

  help:
    silent: true
    cmds:
      - task -l

  ci:
    desc: For CI
    cmds:
      - go mod tidy
      - go mod verify
      - go build
      - go test

  release:
    desc: |
      Build
          ∟ [Ex] task release VERSION=1.2.3
          ∟ [Ex] task release VERSION=1.2.3-beta
    deps:
      - ci
    cmds:
      - sed -i -r 's/const version = ".+"/const version = "{{.VERSION}}"/g' args.go
      - task: ci
      - git add args.go
      - git commit -m 'Version {{.VERSION}}'
      - git tag v{{.VERSION}} -m v{{.VERSION}}
      - git push --tags
      - git push
    preconditions:
      - sh: "[ {{.VERSION}} != '' ]"
        msg: "VERSION is required."
